### PR TITLE
Better viewport limits error message

### PR DESCRIPTION
**Pull request by ivanprado**

### CODE REVIEW

**Comment by lopuhin** [comment]
@kmike could you please review this as well, as I'm not sure about the process for merging splash PRs - e.g. I don't see the tests running for this PR.

**Comment by kmike** [comment]
The change looks good, thanks @ivanprado! A good catch about the tests; it seems the build started, but was killed due to lack of activity on one of the steps. Restarted it now. I'm not sure why it is not showing here. Build: https://travis-ci.org/scrapinghub/splash/builds/651993499

**Comment by kmike** [comment]
Actually, the build for other PR was also stalled: https://travis-ci.org/scrapinghub/splash/builds/649925646. Maybe CI is broken (which is a problem, because it means there won't be a new Docker image).

**Comment by kmike** [comment]
Thanks @ivanprado!

**Comment by kmike** [comment]
Hey @ivanprado! Good news: bulid is fixed, thanks to @imduffy15, @lucywang000 and @Gallaecio. Bad news: tests are failing after this changes, because they were checking error message (see https://travis-ci.org/github/scrapinghub/splash/builds/675004312). Do you think you can take a look? At seems at least one of the failures is related to the fix here.

**Comment by ivanprado** [comment]
Great! @kmike sure, I'm going to investigate.

**Comment by ivanprado** [comment]
Working for a fix in https://github.com/scrapinghub/splash/pull/1021

**Pull request merged**
