### PR TITLE
Show errors in the requested format

### PR DESCRIPTION
**Pull request by Youwotma**
render.html -> HTML error
render.png or jpeg -> Image error
All other endpoints -> JSON error (#226)

### CODE REVIEW

**Comment by immerrr** [comment]
The original issue AFAIU was about parsing and finding out what's happened. I don't think that presenting the error in image format is better than plaintext in that regard. Or is it?

**Comment by pawelmhm** [comment]
I remember there was this suggestion from @kmike https://github.com/scrapinghub/splash/issues/226

**Comment by Youwotma** [comment]
My thoughts to show an image instead of text was indeed to make it easy to
see what happened in case somebody uses 
Or saves the result in a file without checking the response code and
displays it somewhere.

Of course api consumers should always check the responses status code, but
if you forget or don't bother to do it the browser will only display a
broken image with no other clues of what went wrong.

**Comment by immerrr** [comment]
@pawelmhm yes, @kmike's suggestion was about the fact that json is better than plaintext, which i can relate to.
@Youwotma i'd wildly guess that splash is used programmatically more often than visually and it's quite tricky to show images in, for example, spider log. Besides, images embedded as `` sometimes result in http errors too, and I cannot remember from the top of my head anyone serving a pretty "404 Not Found" image instead of a plain HTTP error.

**Comment by kmike** [comment]
You both have a point, but for backwards compatibility it is better to keep png/jpeg error responses simple by default.

In /execute endpoint one can get a screenshot or html of a page even if it returns an error. What about adding an option to do it in render.xxx endpoints, something like `ignore_errors=1`? If this option is active the result will have the same status code, but splash will still render it and return page's html or screenshot. It may also allow to say "I want to render as much as possible in 30s and get a result; I don't care if it is incomplete".

**Comment by kmike** [comment]
@Youwotma could you please add a test which will check the error result explicitly, i.e. that it is a JSON response with 'error' and 'message' fields?

**Comment by Youwotma** [comment]
Yep, will do it tomorrow

**Comment by kmike** [comment]
Thanks!

**Pull request merged**
