### PR TITLE
Update download-qt-installer.sh

### LINKED ISSUE #1100: Image build failing for QT v 5.14.1
After [QT’s open-source repository was down for a few days](https://www.qt.io/blog/problem-with-open-source-downloads), QT components v 5.14.1 (referred to by Splash’s Dockerfile) are no longer available in [QT’s repository](http://download.qt.io/official_releases/qt/). Re-building the Docker image fails.

Reverting to QT version 5.12.10 allows image build to succeed, but the container started from the resulting image crashes with the following log.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/app/splash/server.py", line 12, in <module>
    from splash.qtutils import init_qt_app
  File "/app/splash/qtutils.py", line 15, in <module>
    from PyQt5.QtWebKit import QWebSettings
ImportError: libQt5QmlModels.so.5: cannot open shared object file: No such file or directory
```

### PR DESCRIPTION
**Pull request by rplati**
fixed QT download link

Fixes #1100

### CODE REVIEW

**Review by Gallaecio — APPROVED** [review]
Thanks!

**Comment by rplati** [comment]
Are you in the habit of linking a pull request to an issue? I can’t seem to do that. Or do I just close [#1100](https://github.com/scrapinghub/splash/issues/1100)?

**Comment by Gallaecio** [comment]
> Are you in the habit of linking a pull request to an issue? I can’t seem to do that.

Done :slightly_smiling_face:

[It can be done in the pull request description](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

**Comment by Gallaecio** [comment]
Let’s wait for a second maintainer to have a chance to review it. We usually try to get approval from 2 maintainers before we merge changes. cc @kmike

**Comment by kmike** [comment]
Thanks @rplati and @Gallaecio !

**Pull request merged**
