### PR TITLE
Use a different network_manager for each browser tab

### PR DESCRIPTION
**Pull request by Youwotma**
Another try at fixing #238 and #318

This also removes disk cache support, which is a backwards incompatible change (removes `--cache*` command line flags).

Edit: Also, according to my tests using a different network manager for every doesn't affect how the memory cache works, memory cache is still shared between all the tabs.

### CODE REVIEW

**Comment by kmike** [comment]
Hey @Youwotma,

Sorry for the delay! It is likely I won't have time to check this PR until next week. The code looks fine, but I'd like to check how it works on a large crawl / complex scripts before merging.

**Comment by Youwotma** [comment]
Don't worry, I know you are busy taking care of your new family member (congratulations btw! :smile:).

I'll try to test it a bit tomorrow and write here what I find.

**Comment by kmike** [comment]
Thanks @Youwotma! :baby:

**Comment by Youwotma** [comment]
I ran the benchmark from the benchmark-utility branch (merged into scrapinghub/master and into youwotma/master) and ran it 3 times with `--thread-count 10 --request-count 100` against a newly created docker container (all 3 tests against the same container)
```
== with different network managers
INFO:benchmark:Splash max RSS: 732024832 B
INFO:benchmark:Splash CPU time elapsed: 25.61 sec
INFO:benchmark:Wallclock time elapsed: 25.93 sec

INFO:benchmark:Splash max RSS: 782651392 B
INFO:benchmark:Splash CPU time elapsed: 26.44 sec
INFO:benchmark:Wallclock time elapsed: 26.32 sec

INFO:benchmark:Splash max RSS: 782651392 B
INFO:benchmark:Splash CPU time elapsed: 26.12 sec
INFO:benchmark:Wallclock time elapsed: 26.06 sec

== One network manager
INFO:benchmark:Splash max RSS: 727412736 B
INFO:benchmark:Splash CPU time elapsed: 26.24 sec
INFO:benchmark:Wallclock time elapsed: 26.30 sec

INFO:benchmark:Splash max RSS: 765399040 B
INFO:benchmark:Splash CPU time elapsed: 26.59 sec
INFO:benchmark:Wallclock time elapsed: 26.59 sec

INFO:benchmark:Splash max RSS: 765399040 B
INFO:benchmark:Splash CPU time elapsed: 26.31 sec
INFO:benchmark:Wallclock time elapsed: 25.95 sec
```

Looks like the memory usage has is increased slightly.

**Comment by kmike** [comment]
:+1:  It looks like crawling became faster after this change; for some reason it helped with CPU systime usage on my server.

**Pull request merged**
