### PR TITLE
Several improvements to the web interface

### PR DESCRIPTION
**Pull request by Youwotma**
Several improvements to the web interface:
- Autocomplete `splash:` methods
- Display several images and complex structures in the response
- Allow returning directly splash.png/jpeg()
- Load harviewer lazyly and allow seeing the rest of the response if it doesn't load
- Allow downloading big string as a file (e.g: `splash:html()`)

Looking for feedback and testing

Autocomplete:
splash

New response view:
Default script result
splash

Return array
splash

Return object
splash

Return string
splash

Return long string (`splash:html()`)
splash

Return har
splash

Return image
splash

Structure
splash

### CODE REVIEW

**Comment by Youwotma** [comment]
@kmike can you have a look?

**Comment by kmike** [comment]
@Youwotma :+1: 

Do you think it is possible to enforce/hardcode the PNG -> HAR -> HTML order in the result?

**Comment by kmike** [comment]
It seems you don't need it, but FYI: inspection data for Splash Notebook autocompletion is here: https://github.com/scrapinghub/splash/blob/master/splash/kernel/inspections/splash-auto.json

**Comment by Youwotma** [comment]
@kmike Nice! didn't know about that. That's better that what is using because some aliases that are implemented in lua are not autocompleted.

And maybe I can add inline docs in the popup like in http://ternjs.net/doc/demo/#simple

I'll update the PR with both changes

**Comment by Youwotma** [comment]
I made the changes, the auto-completion now looks like this: http://i.imgur.com/J6WOLMV.png

**Comment by kmike** [comment]
Awesome, thanks!

**Pull request merged**
